# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Arcli < Formula
  desc "CLI for Arc time-series databases"
  homepage "https://github.com/Basekick-Labs/arcli"
  version "26.09.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Basekick-Labs/arcli/releases/download/v26.09.2/arcli_26.09.2_darwin_amd64.tar.gz"
      sha256 "d3cf27ff55b2294bf82c0806afe48d73c68bfb9fd7be2e27f479baf82973eebb"

      define_method(:install) do
        bin.install "arcli"
        bash_completion.install "completions/arcli.bash" => "arcli"
        zsh_completion.install "completions/_arcli"
        fish_completion.install "completions/arcli.fish"
        man1.install Dir["man/*.1"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Basekick-Labs/arcli/releases/download/v26.09.2/arcli_26.09.2_darwin_arm64.tar.gz"
      sha256 "741835c25b9dd69b05ed193e050a958ca12e347b983ee60d47bf91cc670eaca5"

      define_method(:install) do
        bin.install "arcli"
        bash_completion.install "completions/arcli.bash" => "arcli"
        zsh_completion.install "completions/_arcli"
        fish_completion.install "completions/arcli.fish"
        man1.install Dir["man/*.1"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Basekick-Labs/arcli/releases/download/v26.09.2/arcli_26.09.2_linux_amd64.tar.gz"
      sha256 "f236f7af5f199a1797da7ea273b6cb8e140c96830aa61c4c6a9d290874a25f0f"
      define_method(:install) do
        bin.install "arcli"
        bash_completion.install "completions/arcli.bash" => "arcli"
        zsh_completion.install "completions/_arcli"
        fish_completion.install "completions/arcli.fish"
        man1.install Dir["man/*.1"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Basekick-Labs/arcli/releases/download/v26.09.2/arcli_26.09.2_linux_arm64.tar.gz"
      sha256 "40a8e69c6d319a9689ca2cbc7c4a3846012053bc9373459da3e44bd5503941e2"
      define_method(:install) do
        bin.install "arcli"
        bash_completion.install "completions/arcli.bash" => "arcli"
        zsh_completion.install "completions/_arcli"
        fish_completion.install "completions/arcli.fish"
        man1.install Dir["man/*.1"]
      end
    end
  end

  test do
    assert_match "arcli version", shell_output("#{bin}/arcli --version")
  end
end
