# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Arcli < Formula
  desc "CLI for Arc time-series databases"
  homepage "https://github.com/Basekick-Labs/arcli"
  version "26.09.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Basekick-Labs/arcli/releases/download/v26.09.1/arcli_26.09.1_darwin_amd64.tar.gz"
      sha256 "b027a8ea64d33359e404c2ecc8334cf399d47966a21037c6ce047bb5eaf60ddf"

      define_method(:install) do
        bin.install "arcli"
        bash_completion.install "completions/arcli.bash" => "arcli"
        zsh_completion.install "completions/_arcli"
        fish_completion.install "completions/arcli.fish"
        man1.install Dir["man/*.1"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Basekick-Labs/arcli/releases/download/v26.09.1/arcli_26.09.1_darwin_arm64.tar.gz"
      sha256 "820ee1fe46d618ebe9cc8804ecea4e2cc4d5f3d8f9dc83ac7ea2ac7399e72dc4"

      define_method(:install) do
        bin.install "arcli"
        bash_completion.install "completions/arcli.bash" => "arcli"
        zsh_completion.install "completions/_arcli"
        fish_completion.install "completions/arcli.fish"
        man1.install Dir["man/*.1"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Basekick-Labs/arcli/releases/download/v26.09.1/arcli_26.09.1_linux_amd64.tar.gz"
      sha256 "d864b5d5c04e9856ef507680043d8286b6b17631bdb0a911faea590343212658"
      define_method(:install) do
        bin.install "arcli"
        bash_completion.install "completions/arcli.bash" => "arcli"
        zsh_completion.install "completions/_arcli"
        fish_completion.install "completions/arcli.fish"
        man1.install Dir["man/*.1"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Basekick-Labs/arcli/releases/download/v26.09.1/arcli_26.09.1_linux_arm64.tar.gz"
      sha256 "c08c44ba772c352f8bfbe490527f6d3e282872e29bd20bacb00808e3148e626c"
      define_method(:install) do
        bin.install "arcli"
        bash_completion.install "completions/arcli.bash" => "arcli"
        zsh_completion.install "completions/_arcli"
        fish_completion.install "completions/arcli.fish"
        man1.install Dir["man/*.1"]
      end
    end
  end

  test do
    assert_match "arcli version", shell_output("#{bin}/arcli --version")
  end
end
