# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Arcli < Formula
  desc "CLI for Arc time-series databases"
  homepage "https://github.com/Basekick-Labs/arcli"
  version "26.09.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Basekick-Labs/arcli/releases/download/v26.09.3/arcli_26.09.3_darwin_amd64.tar.gz"
      sha256 "6b3c94cdbc4a3c021fffd14dea5a17a4d99034bd152ed765da34abd14941999d"

      define_method(:install) do
        bin.install "arcli"
        bash_completion.install "completions/arcli.bash" => "arcli"
        zsh_completion.install "completions/_arcli"
        fish_completion.install "completions/arcli.fish"
        man1.install Dir["man/*.1"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Basekick-Labs/arcli/releases/download/v26.09.3/arcli_26.09.3_darwin_arm64.tar.gz"
      sha256 "71d39f1363f1622a186fa74587379c152446570e3386c8103d2d9ff1033eeac2"

      define_method(:install) do
        bin.install "arcli"
        bash_completion.install "completions/arcli.bash" => "arcli"
        zsh_completion.install "completions/_arcli"
        fish_completion.install "completions/arcli.fish"
        man1.install Dir["man/*.1"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Basekick-Labs/arcli/releases/download/v26.09.3/arcli_26.09.3_linux_amd64.tar.gz"
      sha256 "032f38a516e57136143db5395844b834fa3d136ed436839ca4abd1a28be9eb88"
      define_method(:install) do
        bin.install "arcli"
        bash_completion.install "completions/arcli.bash" => "arcli"
        zsh_completion.install "completions/_arcli"
        fish_completion.install "completions/arcli.fish"
        man1.install Dir["man/*.1"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Basekick-Labs/arcli/releases/download/v26.09.3/arcli_26.09.3_linux_arm64.tar.gz"
      sha256 "22c9be4fb27174013e3b17034c55ef3b228173e44b1d84276b78af1f0f8d08d3"
      define_method(:install) do
        bin.install "arcli"
        bash_completion.install "completions/arcli.bash" => "arcli"
        zsh_completion.install "completions/_arcli"
        fish_completion.install "completions/arcli.fish"
        man1.install Dir["man/*.1"]
      end
    end
  end

  test do
    assert_match "arcli version", shell_output("#{bin}/arcli --version")
  end
end
